services:
 base:
  build:
    context: .
    dockerfile: Dockerfile
  
    args:
      USERNAME: elyes
      USERID: 1000
  container_name: fw1-cc1
  command: /bin/bash
  tty: true
  stdin_open: true
  volumes:
  - .:/home/user/workspace
  ports:
  - "8000:8000"
  environment:
    PS1: "[ $$(whoami) | \\w ] "
